version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gotodolist_app
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf  # 挂载自定义配置文件
    environment:
      - GIN_MODE=release
      - DATABASE_ADDR=db:3306
      - DATABASE_USER=snow
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=todolist
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: gotodolist_db
    environment:
      - MYSQL_ROOT_PASSWORD=123456  # 设置 root 密码
      - MYSQL_DATABASE=todolist
      - MYSQL_BIND_ADDRESS="0.0.0.0"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:6.2
    container_name: gotodolist_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 10

volumes:
  db_data:
