ZapConfig:
  Filename: "zap.log"
  MaxSize: 5
  MaxAge: 30
  MaxBackups: 1000

DatabaseConfig:
  MysqlConfig:
    Username: "snow"
    Password: 123456
    Addr: db:3306
    DB: todolist
  RedisConfig:
    Addr: redis:6379
    Password: ""
    DB: 0
